// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login').default>>>>
    }
    '/api/test': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test').default>>>>
    }
    '/api/user/:id/profile': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user/[id]/profile').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}